### ISSUE TITLE
Error Fix for 'metaSEM' Installation

### ISSUE THREAD

**Issue by alirezahekmati** [noah-schroeder/runSMA#1]
Hello Dr. Noah,

The first time I tried to install it locally, I encountered some errors. After some research, I found a way to fix it. I think it's worth reporting.

The error was:

> Error: package or namespace load failed for ‘metaSEM’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]): there is no package called ‘quadprog’

I tried running the script multiple times and even restarted R Studio, but the problem persisted.

I finally resolved the issue by adding this code:

```
install.packages("quadprog")
install.packages("metaSEM")
install.packages("metaSEM", dependencies=TRUE)
library(metaSEM)
```

I'm not sure which part exactly solved the problem, but it's working now.

Here is an image of Error

![image](https://github.com/user-attachments/assets/e55a51d8-6dc7-4370-8471-49729be7eaee)

**Comment by noah-schroeder** [comment]
Hmm, that is interesting. I honestly don't know exactly what that error means. I just tried using the code to run SMA locally and I didn't get that error, but of course I already had metaSEM installed from when i created SMA. Did SMA work with that error still? If not, I can remove metaSEM; it's currently only used in creating plots for three-level models and I had considered moving it over to the metafor method for consistency between the 3LMA and 3LMA w/ CHERVE methods anyway, just hadn't had time to do it yet. I can make that change in the next couple weeks if necessary.

**Comment by alirezahekmati** [comment]
after running 
```
install.packages("quadprog")
install.packages("metaSEM")
install.packages("metaSEM", dependencies=TRUE)
library(metaSEM)
```
now it works perfectly fine with your script.
it seems it needed to install the package.

**Comment by noah-schroeder** [comment]
Yea that is peculiar, as metaSEM is one of the packages installed when you run the script (see https://github.com/noah-schroeder/runSMA/blob/main/run_app.R) I don't know what quadprog is, I have never installed that to my knowledge. However, I am glad that it is working! If you run into any other issues please do let me know! This does make me think it may be worthwhile to move over the 3 level analyses to be consistent between models, honestly there is a LOT of code associated with the plots for the three-level analysis that could be simplified by just moving them to the metafor options. I just like the ones that currently exist.
